Основной контент
mariaYunB/travel_landing_page pull request #12
Opened 2020-07-17 16:13 UTC by mariaYunB

fixes #7

2020-07-22 19:43 UTC, o0 reviewed
Неплохое начало, сверстано аккуратно. Вот что меня смущает:
1. Отсутствие бэма
3. Мать-пулреквест, который содержит вообще все изменения: и составные блоки и шаблоны и данные и все на свете. Коммиты при том атомарные, в этом все ок.

2020-07-22 19:43 UTC, o0 commented on data.json
> +  "promo": {
Вот эти данные лишние, потому что они относятся только к отображению, поэтому смело могут жить заинлайнеными в шаблоне. Мы в админке их можем не редактировать и в других отображениях можем не показывать и проживем прекрасно.

2020-07-22 19:43 UTC, o0 commented on data.json
> +  "registration": {
Вот эти данные точно не нужно держать в данных, это точно часть шаблона

2020-07-22 19:43 UTC, o0 commented on templates/main/main.css
> +  width: 300px;
Кажется, что есть проблема с тем, что все размеры прибиты гвоздями, потому что когда я включаю эмулятор мобильного, у меня все перестает помещаться по горизонтали. Кажется, эти блоки должны адаптироваться под то, чтобы вместиться.

![Annotation 2020-07-22 223511](https://user-images.githubusercontent.com/696826/88220643-ebed8400-cc6b-11ea-8787-e631660aa7c9.png)

![Annotation 2020-07-22 223211](https://user-images.githubusercontent.com/696826/88220658-ef810b00-cc6b-11ea-8936-b457df558972.png)

2020-07-22 19:43 UTC, o0 commented on templates/main/main.pug
> +    h2 #{registration.title}
Я бы шел по бэму до конца. Тебе приходится стилизовать эти блоки через селекторы с вложенностью, а смысл бэма как раз в том, чтобы у тебя был любой элемент, до которого можно достучаться по прямому селектору.

2020-07-22 19:43 UTC, o0 commented on templates/main/main.pug
> +    div
`article`?

2020-07-22 19:43 UTC, o0 commented on templates/main/main.pug
> +    h2 #{registration.title}
Думаю, что это касается всего сайта. Давай везде пройдемся по блокам и расставим им имена по бэму

2020-07-22 19:44 UTC, o0 requested changes
Поторопился в нажатии на Ctrl-Enter и не проставил статус, `Request changes`. Теперь справедливость восстановлена.

2020-07-23 19:18 UTC, whoisdaria approved these changes

2020-07-23 19:25 UTC, daria269 commented on templates/main/main.pug
> +      img(src="../../img/" + element.icon)
адрес до картинки точно верный? у меня не открывается 
```suggestion 
      img(src="./img/" + element.icon)
```

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +  icon.style.height = 50 + `px`;
смотри, раз у тебя шаблонная строка(это вот эти апострофы в виде кавычек), то зачем ты используешь конкатенацию? напиши сразу с помощью шаблонной строк полную версию собственно строки

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +  const rect   = el.getBoundingClientRect(),
Если это твоя инициатива так объявлять переменные, то давай лучше каждую объявим отдельно, если вас так учит Игорь, то я потерплю =) Но вообще, так было модно лет 7 назад, но потом даже Яндекс отказались от такого объявления. Но нам это не важно. Ты учишься и получаешь два взгляда на одни и те же вещи, оба из которых имеют право на жизнь. Так что даже хорошо, что мы с Игорем расходимся в рекомендациях. Потому что это расширяет вашу вариативность.

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +      vWidth   = window.innerWidth || document.documentElement.clientWidth,
document.documentElement === html, но я бы рекомендовала не считать от html, а считать от body. То есть document.body так как это первый элемент именно разметки основной, а не вспомогательной.

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +      efp      = (x, y) => document.elementFromPoint(x, y);
сокращение efp заставило меня поискать, что это такое, что говорит нам о том, что этот нейминг не очевиден, лучше добавить буковок и сделать так, чтобы с разбегу было понятно, что это такое

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +  if (rect.right < 0 || rect.bottom < 0 || rect.left > vWidth || rect.top > vHeight)
длинные условия хорошо выносить в переменные с говорящим названием, типа isElementInViewport  = (условие), а в if писать уже if  ( isElementInViewport)  - сильно улучшает читаемость кода в дальнейшем. Не нужно вдумыватьяс что это за условие, а читаешь и ясно о чем речь

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +  if (rect.right < 0 || rect.bottom < 0 || rect.left > vWidth || rect.top > vHeight)
Я не знаю полную задачу, но за нахождением элемента во вьюпорте хорошо следить с помощью https://developer.mozilla.org/ru/docs/Web/API/Intersection_Observer_API: дешевле чем расчеты, встроенно в браузер и лучше оптимизируется. Разберите с командой, полезная шутка даже если и не найдете применение

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +window.addEventListener(`scroll`, () => {
ооо, да, вот для этого как раз есть intersection observer , но если не сможете, то и так норм

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +        icon.style.height = 50 + `px`;
тоже самое про шаблонные строки

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +    setTimeout(() => {
А если быстро скроллить, то у нас будет висеть куча отложенных вызовов, которые зачем-то отработают. Тут можно посмотреть в сторону throttle/debounce (https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf), но это если вы не заюзаете обзервер, обзервер, вроде бы оптимизирует это за вас. То есть это все на командное обсуждение. Уверена, что Женя не умеет писать тротлы и дебаунсы =) Их вообще мало кто с разбега писать хорошо может

2020-08-27 20:34 UTC, Yorkina commented on js/effect_for_icons.js
> +    setTimeout(() => {
Хотя уточните у Игоря, не перегибаю ли я вам по сложности =)

2020-08-27 20:34 UTC, Yorkina commented on templates/main/main.pug
> +      img.privileges__icon(src="../../img/" + element.icon)
а можно использовать шаблонную строку =)

2020-10-14 15:47 UTC, merged